import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import vercel from "@astrojs/vercel";
import icon from "astro-icon";

import react from "@astrojs/react";

export default defineConfig({
  site: "https://thejands.in",
  output: "static",
  adapter: vercel(),
  trailingSlash: "never",
  compressHTML: true,
  integrations: [
    icon(),
    sitemap({
      filter: (page) =>
        !page.includes("/blog") &&
        !page.includes("/widgets") &&
        !page.includes("/admin"),
      changefreq: "weekly",
      priority: 0.7,
    }),
    react(),
  ],
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "viewport",
  },
  build: {
    inlineStylesheets: "auto",
  },
  vite: {
    server: {
      watch: {
        // Generated by Astro content sync; watching causes restart/HMR races on iCloud.
        ignored: ["**/.astro/**", "**/.vercel/**"],
      },
    },
    optimizeDeps: {
      include: ["motion/react", "react", "react-dom", "react/jsx-dev-runtime"],
    },
  },
});