import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import vercel from "@astrojs/vercel";
import icon from "astro-icon";

import react from "@astrojs/react";

export default defineConfig({
  site: "https://thejands.in",
  output: "static",
  adapter: vercel(),
  trailingSlash: "never",
  compressHTML: true,
  integrations: [
    icon(),
    sitemap({
      filter: (page) =>
        !page.includes("/blog") &&
        !page.includes("/widgets") &&
        !page.includes("/admin"),
      // Careers is SSR — add manually so it appears in the sitemap
      customPages: ["https://thejands.in/careers"],
      changefreq: "weekly",
      // Per-page priorities: home > landing pages > core pages > legal
      serialize(item) {
        const url = item.url;
        if (url === "https://thejands.in" || url === "https://thejands.in/") {
          return { ...item, priority: 1.0, changefreq: "weekly" };
        }
        if (url.includes("/services/") && url !== "https://thejands.in/services") {
          return { ...item, priority: 0.9, changefreq: "weekly" };
        }
        if (
          url.includes("/services") ||
          url.includes("/about") ||
          url.includes("/process") ||
          url.includes("/contact") ||
          url.includes("/careers")
        ) {
          return { ...item, priority: 0.8, changefreq: "weekly" };
        }
        // Legal / misc pages
        return { ...item, priority: 0.4, changefreq: "monthly" };
      },
    }),
    react(),
  ],
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "viewport",
  },
  build: {
    inlineStylesheets: "auto",
  },
  vite: {
    server: {
      watch: {
        // Generated by Astro content sync; watching causes restart/HMR races on iCloud.
        ignored: ["**/.astro/**", "**/.vercel/**"],
      },
    },
    optimizeDeps: {
      include: ["motion/react", "react", "react-dom", "react/jsx-dev-runtime"],
    },
  },
});